linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - testifylint
    - goimports
    - goconst

issues:
  exclude-dirs:
    - .github
    - docs